[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(self), camera=()"
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "default-src 'self' https://telegram.org https://*.t.me https://*.telegram.org; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://telegram.org https://unpkg.com https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline'; img-src * data: blob:; connect-src *; frame-ancestors 'self' https://*.t.me https://*.telegram.org;"

# Optionally inject API base at runtime via snippet if needed
